# Generated by Django 6.0.5 on 2026-05-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_remove_booking_unique_slot_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorstudentlink',
            name='student_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='supervisorstudentlink',
            name='supervisor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
