# Generated by Django 6.0.5 on 2026-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0004_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='supervisor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
