# Generated by Django 6.0.5 on 2026-05-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0006_booking_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='supervisor_name',
            new_name='co_supervisor',
        ),
    ]
