# Generated by Django 6.0.5 on 2026-07-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0009_panel_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['day__date', 'sort_order', 'name']},
        ),
    ]
