# Generated by Django 6.0.5 on 2026-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0011_booking_booking_type_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('syndicate', 'Syndicate'), ('summative', 'Summative'), ('group', 'Group')], default='syndicate', max_length=20),
        ),
    ]
